version: '3'
services:
  app:
    image: neromorph/laravel-boilerplate:latest
    container_name: app
    restart: unless-stopped
    tty: true
    env_file: .env
    depends_on:
      - cache
    networks:
      - laravel-prod

  web_server:
    image: neromorph/laravel-boilerplate-web:latest
    container_name: web_server
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    depends_on:
      - app
    networks:
      - laravel-prod

  cache:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    networks:
      - laravel-prod
 
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel-prod

#Docker Networks
networks:
  laravel-prod:
    driver: bridge
